
// This file has been generated by the GUI designer. Do not modify.
namespace LinXbox360isoBurner
{
	public partial class About
	{
		private global::Gtk.VBox vbox4;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Image image;

		private global::Gtk.VBox vbox6;

		private global::Gtk.Label label2;

		private global::Gtk.Label label3;

		private global::Gtk.Label label4;

		private global::Gtk.HButtonBox hbuttonbox3;

		private global::Gtk.Button button;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LinXbox360isoBurner.About
			this.Name = "LinXbox360isoBurner.About";
			this.Title = "About";
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("LinXbox360isoBurner.icon.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			this.Gravity = ((global::Gdk.Gravity)(5));
			// Container child LinXbox360isoBurner.About.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.image = new global::Gtk.Image ();
			this.image.Name = "image";
			this.image.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("LinXbox360isoBurner.icon.png");
			this.hbox2.Add (this.image);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.image]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = "LinXbox360isoBurner ver. 0.2.0";
			this.label2.Justify = ((global::Gtk.Justification)(2));
			this.vbox6.Add (this.label2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.label2]));
			w2.Position = 0;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = "Author: Andrey Sizov <AndrSizov@gmail.com>";
			this.label3.Justify = ((global::Gtk.Justification)(2));
			this.vbox6.Add (this.label3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.label3]));
			w3.Position = 1;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = "This programm is distriuted under GNU GPL v.3\nYou can get sourse code via svn repository\nhttp://linxboxisoburner.googlecode.com/svn/trunk/linxboxisoburner";
			this.label4.Justify = ((global::Gtk.Justification)(2));
			this.vbox6.Add (this.label4);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.label4]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.hbox2.Add (this.vbox6);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox6]));
			w5.PackType = ((global::Gtk.PackType)(1));
			w5.Position = 1;
			w5.Fill = false;
			this.vbox4.Add (this.hbox2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox2]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbuttonbox3 = new global::Gtk.HButtonBox ();
			this.hbuttonbox3.Name = "hbuttonbox3";
			// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.button = new global::Gtk.Button ();
			this.button.CanFocus = true;
			this.button.Name = "button";
			this.button.UseUnderline = true;
			this.button.Label = "Close";
			this.hbuttonbox3.Add (this.button);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3[this.button]));
			w7.Expand = false;
			w7.Fill = false;
			this.vbox4.Add (this.hbuttonbox3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbuttonbox3]));
			w8.Position = 1;
			this.Add (this.vbox4);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 613;
			this.DefaultHeight = 195;
			this.Show ();
			this.button.Clicked += new global::System.EventHandler (this.OnButtonClicked);
		}
	}
}
