
// This file has been generated by the GUI designer. Do not modify.
namespace LinXbox360isoBurner
{
	public partial class BurningWindow
	{
		private global::Gtk.Fixed fixed_burn;

		private global::Gtk.Label label_status;

		private global::Gtk.Button button_cancel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LinXbox360isoBurner.BurningWindow
			this.Name = "LinXbox360isoBurner.BurningWindow";
			this.Title = "Burning...";
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("LinXbox360isoBurner.icon.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Resizable = false;
			this.AllowGrow = false;
			this.DestroyWithParent = true;
			this.Gravity = ((global::Gdk.Gravity)(5));
			this.SkipPagerHint = true;
			// Container child LinXbox360isoBurner.BurningWindow.Gtk.Container+ContainerChild
			this.fixed_burn = new global::Gtk.Fixed ();
			this.fixed_burn.Name = "fixed_burn";
			this.fixed_burn.HasWindow = false;
			// Container child fixed_burn.Gtk.Fixed+FixedChild
			this.label_status = new global::Gtk.Label ();
			this.label_status.Name = "label_status";
			this.label_status.Xpad = 96;
			this.label_status.Ypad = 5;
			this.label_status.Xalign = 1f;
			this.label_status.LabelProp = "...";
			this.label_status.Justify = ((global::Gtk.Justification)(2));
			this.label_status.SingleLineMode = true;
			this.fixed_burn.Add (this.label_status);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed_burn[this.label_status]));
			w1.X = 1;
			w1.Y = 19;
			// Container child fixed_burn.Gtk.Fixed+FixedChild
			this.button_cancel = new global::Gtk.Button ();
			this.button_cancel.CanFocus = true;
			this.button_cancel.Name = "button_cancel";
			this.button_cancel.UseUnderline = true;
			this.button_cancel.Label = "Cancel";
			this.fixed_burn.Add (this.button_cancel);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed_burn[this.button_cancel]));
			w2.X = 75;
			w2.Y = 53;
			this.Add (this.fixed_burn);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 211;
			this.DefaultHeight = 124;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.SizeAllocated += new global::Gtk.SizeAllocatedHandler (this.OnSizeAllocated);
			this.WindowStateEvent += new global::Gtk.WindowStateEventHandler (this.OnWindowStateEvent);
		}
	}
}
