// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.Fixed @fixed;
    
    private Gtk.Button button_ok;
    
    private Gtk.Label label1;
    
    private Gtk.Entry entry;
    
    private Gtk.FileChooserButton filechooserbutton;
    
    private Gtk.Button button_exit;
    
    private Gtk.HButtonBox hbuttonbox5;
    
    private Gtk.Label label2;
    
    private Gtk.Entry entry_dvd;
    
    private Gtk.CheckButton checkbutton_dryrun;
    
    private Gtk.Label label3;
    
    private Gtk.ComboBox combobox_speed;
    
    private Gtk.Button button_autodvdrw;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = "LinXbox360isoBurner";
        this.Icon = Gdk.Pixbuf.LoadFromResource("icon.png");
        this.WindowPosition = ((Gtk.WindowPosition)(1));
        this.Resizable = false;
        this.AllowGrow = false;
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.@fixed = new Gtk.Fixed();
        this.@fixed.Name = "fixed";
        this.@fixed.HasWindow = false;
        // Container child fixed.Gtk.Fixed+FixedChild
        this.button_ok = new Gtk.Button();
        this.button_ok.Sensitive = false;
        this.button_ok.CanFocus = true;
        this.button_ok.Name = "button_ok";
        this.button_ok.UseUnderline = true;
        this.button_ok.Label = "Burn";
        this.@fixed.Add(this.button_ok);
        Gtk.Fixed.FixedChild w1 = ((Gtk.Fixed.FixedChild)(this.@fixed[this.button_ok]));
        w1.X = 20;
        w1.Y = 220;
        // Container child fixed.Gtk.Fixed+FixedChild
        this.label1 = new Gtk.Label();
        this.label1.Name = "label1";
        this.label1.Xalign = 0F;
        this.label1.LabelProp = ".dvd file:";
        this.@fixed.Add(this.label1);
        Gtk.Fixed.FixedChild w2 = ((Gtk.Fixed.FixedChild)(this.@fixed[this.label1]));
        w2.X = 15;
        w2.Y = 13;
        // Container child fixed.Gtk.Fixed+FixedChild
        this.entry = new Gtk.Entry();
        this.entry.CanFocus = true;
        this.entry.Name = "entry";
        this.entry.IsEditable = true;
        this.entry.InvisibleChar = '●';
        this.@fixed.Add(this.entry);
        Gtk.Fixed.FixedChild w3 = ((Gtk.Fixed.FixedChild)(this.@fixed[this.entry]));
        w3.X = 15;
        w3.Y = 40;
        // Container child fixed.Gtk.Fixed+FixedChild
        this.filechooserbutton = new Gtk.FileChooserButton("", ((Gtk.FileChooserAction)(0)));
        this.filechooserbutton.Name = "filechooserbutton";
        this.filechooserbutton.ShowHidden = true;
        this.@fixed.Add(this.filechooserbutton);
        Gtk.Fixed.FixedChild w4 = ((Gtk.Fixed.FixedChild)(this.@fixed[this.filechooserbutton]));
        w4.X = 213;
        w4.Y = 40;
        // Container child fixed.Gtk.Fixed+FixedChild
        this.button_exit = new Gtk.Button();
        this.button_exit.CanFocus = true;
        this.button_exit.Name = "button_exit";
        this.button_exit.UseUnderline = true;
        this.button_exit.Label = "Exit ";
        this.@fixed.Add(this.button_exit);
        Gtk.Fixed.FixedChild w5 = ((Gtk.Fixed.FixedChild)(this.@fixed[this.button_exit]));
        w5.X = 247;
        w5.Y = 220;
        // Container child fixed.Gtk.Fixed+FixedChild
        this.hbuttonbox5 = new Gtk.HButtonBox();
        this.hbuttonbox5.Name = "hbuttonbox5";
        this.@fixed.Add(this.hbuttonbox5);
        Gtk.Fixed.FixedChild w6 = ((Gtk.Fixed.FixedChild)(this.@fixed[this.hbuttonbox5]));
        w6.X = 76;
        w6.Y = 82;
        // Container child fixed.Gtk.Fixed+FixedChild
        this.label2 = new Gtk.Label();
        this.label2.Name = "label2";
        this.label2.LabelProp = "DVD recorder:";
        this.@fixed.Add(this.label2);
        Gtk.Fixed.FixedChild w7 = ((Gtk.Fixed.FixedChild)(this.@fixed[this.label2]));
        w7.X = 15;
        w7.Y = 78;
        // Container child fixed.Gtk.Fixed+FixedChild
        this.entry_dvd = new Gtk.Entry();
        this.entry_dvd.CanFocus = true;
        this.entry_dvd.Name = "entry_dvd";
        this.entry_dvd.Text = "/dev/";
        this.entry_dvd.IsEditable = true;
        this.entry_dvd.InvisibleChar = '●';
        this.@fixed.Add(this.entry_dvd);
        Gtk.Fixed.FixedChild w8 = ((Gtk.Fixed.FixedChild)(this.@fixed[this.entry_dvd]));
        w8.X = 15;
        w8.Y = 105;
        // Container child fixed.Gtk.Fixed+FixedChild
        this.checkbutton_dryrun = new Gtk.CheckButton();
        this.checkbutton_dryrun.CanFocus = true;
        this.checkbutton_dryrun.Name = "checkbutton_dryrun";
        this.checkbutton_dryrun.Label = "dry-run";
        this.checkbutton_dryrun.DrawIndicator = true;
        this.checkbutton_dryrun.UseUnderline = true;
        this.@fixed.Add(this.checkbutton_dryrun);
        Gtk.Fixed.FixedChild w9 = ((Gtk.Fixed.FixedChild)(this.@fixed[this.checkbutton_dryrun]));
        w9.X = 15;
        w9.Y = 183;
        // Container child fixed.Gtk.Fixed+FixedChild
        this.label3 = new Gtk.Label();
        this.label3.Name = "label3";
        this.label3.LabelProp = "Burning speed:";
        this.@fixed.Add(this.label3);
        Gtk.Fixed.FixedChild w10 = ((Gtk.Fixed.FixedChild)(this.@fixed[this.label3]));
        w10.X = 20;
        w10.Y = 149;
        // Container child fixed.Gtk.Fixed+FixedChild
        this.combobox_speed = Gtk.ComboBox.NewText();
        this.combobox_speed.AppendText("2");
        this.combobox_speed.AppendText("3");
        this.combobox_speed.AppendText("4");
        this.combobox_speed.Name = "combobox_speed";
        this.combobox_speed.Active = 0;
        this.@fixed.Add(this.combobox_speed);
        Gtk.Fixed.FixedChild w11 = ((Gtk.Fixed.FixedChild)(this.@fixed[this.combobox_speed]));
        w11.X = 213;
        w11.Y = 143;
        // Container child fixed.Gtk.Fixed+FixedChild
        this.button_autodvdrw = new Gtk.Button();
        this.button_autodvdrw.CanFocus = true;
        this.button_autodvdrw.Name = "button_autodvdrw";
        this.button_autodvdrw.UseUnderline = true;
        this.button_autodvdrw.Label = "auto detect";
        this.@fixed.Add(this.button_autodvdrw);
        Gtk.Fixed.FixedChild w12 = ((Gtk.Fixed.FixedChild)(this.@fixed[this.button_autodvdrw]));
        w12.X = 213;
        w12.Y = 106;
        this.Add(this.@fixed);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 314;
        this.DefaultHeight = 287;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.button_ok.Clicked += new System.EventHandler(this.OnButtonOkClicked);
        this.entry.Changed += new System.EventHandler(this.OnEntryChanged);
        this.filechooserbutton.SelectionChanged += new System.EventHandler(this.OnFilechooserbuttonSelectionChanged);
        this.button_exit.Clicked += new System.EventHandler(this.OnButtonExitClicked);
        this.entry_dvd.Changed += new System.EventHandler(this.OnEntryDvdChanged);
        this.checkbutton_dryrun.Pressed += new System.EventHandler(this.OnCheckbuttonDryrunPressed);
        this.button_autodvdrw.Clicked += new System.EventHandler(this.OnButtonAutodvdrwClicked);
    }
}
