
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action HelpAction;
	private global::Gtk.Action cdromAction;
	private global::Gtk.Action ExitAction;
	private global::Gtk.Action AboutAction;
	private global::Gtk.Action BurnAction;
	private global::Gtk.Action propertiesAction;
	private global::Gtk.ToggleAction PreferencesAction;
	private global::Gtk.Action PreferencesAction1;
	private global::Gtk.Action ExitAction1;
	private global::Gtk.Action FileAction1;
	private global::Gtk.Action HelpAction1;
	private global::Gtk.Action cdromAction1;
	private global::Gtk.Action preferencesAction;
	private global::Gtk.Action stopAction;
	private global::Gtk.Action AboutAction1;
	private global::Gtk.VBox vbox;
	private global::Gtk.MenuBar menubar;
	private global::Gtk.HBox hbox1;
	private global::Gtk.HBox hbox6;
	private global::Gtk.Label label4;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Entry entry;
	private global::Gtk.Fixed fixed2;
	private global::Gtk.FileChooserButton filechooserbutton;
	private global::Gtk.HBox hbox7;
	private global::Gtk.Label label5;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Entry entry_dvd;
	private global::Gtk.Fixed fixed3;
	private global::Gtk.HButtonBox hbuttonbox3;
	private global::Gtk.Button button9;
	private global::Gtk.Fixed fixed4;
	private global::Gtk.CheckButton checkbutton_dryrun;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Label label3;
	private global::Gtk.ComboBox combobox_speed;
	private global::Gtk.HButtonBox hbuttonbox;
	private global::Gtk.Button button_ok;
	private global::Gtk.Button button_exit;
    
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", "File", null, null);
		this.FileAction.ShortLabel = "File";
		w1.Add (this.FileAction, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", "Help", null, null);
		this.HelpAction.ShortLabel = "Help";
		w1.Add (this.HelpAction, null);
		this.cdromAction = new global::Gtk.Action ("cdromAction", "Burn...", null, "gtk-cdrom");
		this.cdromAction.ShortLabel = "Burn...";
		w1.Add (this.cdromAction, null);
		this.ExitAction = new global::Gtk.Action ("ExitAction", "Exit", null, null);
		this.ExitAction.ShortLabel = "Exit";
		w1.Add (this.ExitAction, null);
		this.AboutAction = new global::Gtk.Action ("AboutAction", "About...", null, null);
		this.AboutAction.ShortLabel = "About...";
		w1.Add (this.AboutAction, null);
		this.BurnAction = new global::Gtk.Action ("BurnAction", "Burn...", null, null);
		this.BurnAction.Sensitive = false;
		this.BurnAction.ShortLabel = "Burn...";
		w1.Add (this.BurnAction, null);
		this.propertiesAction = new global::Gtk.Action ("propertiesAction", "Preferences...", null, "gtk-properties");
		this.propertiesAction.ShortLabel = "Preferences...";
		w1.Add (this.propertiesAction, null);
		this.PreferencesAction = new global::Gtk.ToggleAction ("PreferencesAction", "Preferences...", null, null);
		this.PreferencesAction.ShortLabel = "Preferences...";
		w1.Add (this.PreferencesAction, null);
		this.PreferencesAction1 = new global::Gtk.Action ("PreferencesAction1", "Preferences...", null, null);
		this.PreferencesAction1.ShortLabel = "Preferences...";
		w1.Add (this.PreferencesAction1, null);
		this.ExitAction1 = new global::Gtk.Action ("ExitAction1", "Exit", null, null);
		this.ExitAction1.ShortLabel = "Exit";
		w1.Add (this.ExitAction1, null);
		this.FileAction1 = new global::Gtk.Action ("FileAction1", "File", null, null);
		this.FileAction1.ShortLabel = "File";
		w1.Add (this.FileAction1, null);
		this.HelpAction1 = new global::Gtk.Action ("HelpAction1", "Help", null, null);
		this.HelpAction1.ShortLabel = "Help";
		w1.Add (this.HelpAction1, null);
		this.cdromAction1 = new global::Gtk.Action ("cdromAction1", "Burn...", null, "gtk-cdrom");
		this.cdromAction1.Sensitive = false;
		this.cdromAction1.ShortLabel = "Burn...";
		w1.Add (this.cdromAction1, null);
		this.preferencesAction = new global::Gtk.Action ("preferencesAction", "Preferences...", null, "gtk-preferences");
		this.preferencesAction.ShortLabel = "Preferences...";
		w1.Add (this.preferencesAction, null);
		this.stopAction = new global::Gtk.Action ("stopAction", "Exit", null, "gtk-stop");
		this.stopAction.ShortLabel = "Exit";
		w1.Add (this.stopAction, null);
		this.AboutAction1 = new global::Gtk.Action ("AboutAction1", "About...", null, null);
		this.AboutAction1.ShortLabel = "About...";
		w1.Add (this.AboutAction1, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = "LinXbox360isoBurner";
		this.Icon = global::Gdk.Pixbuf.LoadFromResource ("LinXbox360isoBurner.icon.png");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.Resizable = false;
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox = new global::Gtk.VBox ();
		this.vbox.Name = "vbox";
		this.vbox.Spacing = 6;
		// Container child vbox.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar'><menu name='FileAction1' action='FileAction1'><menuitem name='cdromAction1' action='cdromAction1'/><menuitem name='preferencesAction' action='preferencesAction'/><menuitem name='stopAction' action='stopAction'/></menu><menu name='HelpAction1' action='HelpAction1'><menuitem name='AboutAction1' action='AboutAction1'/></menu></menubar></ui>");
		this.menubar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar")));
		this.menubar.Name = "menubar";
		this.vbox.Add (this.menubar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox [this.menubar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = ".dvd file:";
		this.hbox6.Add (this.label4);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label4]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		w3.Padding = ((uint)(15));
		this.hbox1.Add (this.hbox6);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hbox6]));
		w4.Position = 0;
		this.vbox.Add (this.hbox1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox [this.hbox1]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.entry = new global::Gtk.Entry ();
		this.entry.CanFocus = true;
		this.entry.Name = "entry";
		this.entry.IsEditable = true;
		this.entry.InvisibleChar = '●';
		this.hbox2.Add (this.entry);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.entry]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Padding = ((uint)(15));
		// Container child hbox2.Gtk.Box+BoxChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		this.hbox2.Add (this.fixed2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.fixed2]));
		w7.Position = 1;
		// Container child hbox2.Gtk.Box+BoxChild
		this.filechooserbutton = new global::Gtk.FileChooserButton ("Выберите файл", ((global::Gtk.FileChooserAction)(0)));
		this.filechooserbutton.Name = "filechooserbutton";
		this.hbox2.Add (this.filechooserbutton);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.filechooserbutton]));
		w8.PackType = ((global::Gtk.PackType)(1));
		w8.Position = 2;
		w8.Expand = false;
		w8.Padding = ((uint)(15));
		this.vbox.Add (this.hbox2);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox [this.hbox2]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = "DVD-RW drive:";
		this.hbox7.Add (this.label5);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label5]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		w10.Padding = ((uint)(15));
		this.vbox.Add (this.hbox7);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox [this.hbox7]));
		w11.Position = 3;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.entry_dvd = new global::Gtk.Entry ();
		this.entry_dvd.CanFocus = true;
		this.entry_dvd.Name = "entry_dvd";
		this.entry_dvd.Text = "/dev/";
		this.entry_dvd.IsEditable = true;
		this.entry_dvd.InvisibleChar = '●';
		this.hbox3.Add (this.entry_dvd);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.entry_dvd]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		w12.Padding = ((uint)(15));
		// Container child hbox3.Gtk.Box+BoxChild
		this.fixed3 = new global::Gtk.Fixed ();
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		this.hbox3.Add (this.fixed3);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.fixed3]));
		w13.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.hbuttonbox3 = new global::Gtk.HButtonBox ();
		this.hbuttonbox3.Name = "hbuttonbox3";
		// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
		this.button9 = new global::Gtk.Button ();
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.button9.Label = "Autodetect";
		this.hbuttonbox3.Add (this.button9);
		global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3 [this.button9]));
		w14.Expand = false;
		w14.Fill = false;
		this.hbox3.Add (this.hbuttonbox3);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.hbuttonbox3]));
		w15.Position = 2;
		this.vbox.Add (this.hbox3);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox [this.hbox3]));
		w16.Position = 4;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox.Gtk.Box+BoxChild
		this.fixed4 = new global::Gtk.Fixed ();
		this.fixed4.Name = "fixed4";
		this.fixed4.HasWindow = false;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.checkbutton_dryrun = new global::Gtk.CheckButton ();
		this.checkbutton_dryrun.CanFocus = true;
		this.checkbutton_dryrun.Name = "checkbutton_dryrun";
		this.checkbutton_dryrun.Label = "dry-run";
		this.checkbutton_dryrun.DrawIndicator = true;
		this.checkbutton_dryrun.UseUnderline = true;
		this.fixed4.Add (this.checkbutton_dryrun);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.checkbutton_dryrun]));
		w17.X = 15;
		w17.Y = 3;
		this.vbox.Add (this.fixed4);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox [this.fixed4]));
		w18.Position = 5;
		// Container child vbox.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = "Burning speed:";
		this.hbox5.Add (this.label3);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label3]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		w19.Padding = ((uint)(15));
		// Container child hbox5.Gtk.Box+BoxChild
		this.combobox_speed = global::Gtk.ComboBox.NewText ();
		this.combobox_speed.AppendText ("2");
		this.combobox_speed.AppendText ("4");
		this.combobox_speed.AppendText ("6");
		this.combobox_speed.Name = "combobox_speed";
		this.combobox_speed.Active = 0;
		this.hbox5.Add (this.combobox_speed);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.combobox_speed]));
		w20.PackType = ((global::Gtk.PackType)(1));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		w20.Padding = ((uint)(49));
		this.vbox.Add (this.hbox5);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox [this.hbox5]));
		w21.Position = 6;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox.Gtk.Box+BoxChild
		this.hbuttonbox = new global::Gtk.HButtonBox ();
		this.hbuttonbox.Name = "hbuttonbox";
		this.hbuttonbox.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
		// Container child hbuttonbox.Gtk.ButtonBox+ButtonBoxChild
		this.button_ok = new global::Gtk.Button ();
		this.button_ok.Sensitive = false;
		this.button_ok.CanFocus = true;
		this.button_ok.Name = "button_ok";
		this.button_ok.UseUnderline = true;
		this.button_ok.Label = "Burn";
		this.hbuttonbox.Add (this.button_ok);
		global::Gtk.ButtonBox.ButtonBoxChild w22 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox [this.button_ok]));
		w22.Expand = false;
		w22.Fill = false;
		w22.Padding = ((uint)(15));
		// Container child hbuttonbox.Gtk.ButtonBox+ButtonBoxChild
		this.button_exit = new global::Gtk.Button ();
		this.button_exit.CanFocus = true;
		this.button_exit.Name = "button_exit";
		this.button_exit.UseUnderline = true;
		this.button_exit.Label = "Exit";
		this.hbuttonbox.Add (this.button_exit);
		global::Gtk.ButtonBox.ButtonBoxChild w23 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox [this.button_exit]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		this.vbox.Add (this.hbuttonbox);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox [this.hbuttonbox]));
		w24.Position = 8;
		w24.Expand = false;
		this.Add (this.vbox);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 396;
		this.DefaultHeight = 328;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.ExitAction.Activated += new global::System.EventHandler (this.OnButtonExitClicked);
		this.AboutAction.Activated += new global::System.EventHandler (this.OnAboutActionActivated);
		this.BurnAction.Activated += new global::System.EventHandler (this.OnButtonOkClicked);
		this.propertiesAction.Activated += new global::System.EventHandler (this.OnPreferencesActionActivated);
		this.PreferencesAction.Activated += new global::System.EventHandler (this.OnPreferencesActionActivated);
		this.cdromAction1.Activated += new global::System.EventHandler (this.OnButtonOkClicked);
		this.preferencesAction.Activated += new global::System.EventHandler (this.OnPreferencesActionActivated);
		this.stopAction.Activated += new global::System.EventHandler (this.OnButtonExitClicked);
		this.AboutAction1.Activated += new global::System.EventHandler (this.OnAboutActionActivated);
		this.entry.Changed += new global::System.EventHandler (this.OnEntryChanged);
		this.filechooserbutton.SelectionChanged += new global::System.EventHandler (this.OnFilechooserbuttonSelectionChanged);
		this.entry_dvd.Changed += new global::System.EventHandler (this.OnEntryChanged);
		this.button9.Clicked += new global::System.EventHandler (this.OnButtonAutodvdrwClicked);
		this.checkbutton_dryrun.Clicked += new global::System.EventHandler (this.OnCheckbuttonDryrunPressed);
		this.button_ok.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		this.button_exit.Clicked += new global::System.EventHandler (this.OnButtonExitClicked);
	}
}
